### ISSUE TITLE
SSR: No navigation results when using HTTP cache

### ISSUE THREAD

**Issue by SvenHerrmann** [FACT-Finder-Web-Components/shopware6-plugin#108] opened 2023-01-06 09:20 UTC
We are working with ssr-branch, currently 23b549217b90880e096f8882e6358c25d8739a2b on Shopware 6.4.12.0

When we enable HTTP caching in Shopware, no SSR navigation searches are executed.

The reason seems to be:

In NavigationPageLoadedEvent the request object gets an attribute with the current categoryPath:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/23b549217b90880e096f8882e6358c25d8739a2b/src/Subscriber/CategoryPageSubscriber.php#L68

In BeforeSendResponseEvent this attribute is read in order to execute the search:
https://github.com/FACT-Finder-Web-Components/shopware6-plugin/blob/23b549217b90880e096f8882e6358c25d8739a2b/src/Subscriber/CategoryPageResponseSubscriber.php#L40

When the response has not been cached yet, the fetch-mechanism of the HTTP cache works on a clone of the request:
https://github.com/symfony/http-kernel/blob/519658daef172cfb3a5cc5b78ce5eb0fb0ff3691/HttpCache/HttpCache.php#L441

So in the NavigationPageLoadedEvent the clone gets an additional attribute while in BeforeSendResponseEvent the attribute is read from the original request.

Next problem: when the response has already been cached, the NavigationPageLoadedEvent is never fired, so the necessary attribute gets never added.

**Comment by grzegorz-jamroz** [comment] 2023-01-11 09:23
Hi @SvenHerrmann thank you for reporting. Solution has been pushed to ssr-branch. 

I checked when `NavigationPageLoadedEvent` and `BeforeSendResponseEvent` are fired. I saw that they are triggered always - it doesn't matter HTTP cache is enabled or not.

I hope my solution will help but please let me know in case of any further problems.

**Comment by SvenHerrmann** [comment] 2023-01-11 16:22
Hi @grzegorz-jamroz 

if HTTP cache is enabled:
`NavigationPageLoadedEvent` is only fired on the first request for a category.
After that, the content is cached and on the second request, the event is not fired any more.

Isn't it a bit dangerous to save the categoryPath in session?
Couldn't there be edge cases of users opening multiple categories at the same time in multiple browser tabs and then getting the category content from a wrong category?
I mean: save the categoryPath from Tab A in session, then (bad timing ;-)) save categoryPath from Tab B in session, then read the categoryPath for Tag A out of the session (which is the categoryPath for Tab B in that moment).

**Comment by grzegorz-jamroz** [comment] 2023-01-12 06:44
Hi @SvenHerrmann,

Thank you for your reply.

> if HTTP cache is enabled:
> NavigationPageLoadedEvent is only fired on the first request for a category.
> After that, the content is cached and on the second request, the event is not fired any more."

Finally I discovered how to reproduce it - I have to be in production mode then it works as you said.

> An example combining both problems:
> 
> enable HTTP cache
> open category A -> all is fine
> open category B -> all is fine
> (now both categories are cached)
> open category A -> you see content of category B

You have right - I tried this and is exactly as you said.

I will search for some solution today to resolve this issue in another way.

**Comment by grzegorz-jamroz** [comment] 2023-01-12 13:36
Hi @SvenHerrmann 

I pushed fix https://github.com/FACT-Finder-Web-Components/shopware6-plugin/commit/f473d56c95d271d6dc91b828137c405b0f275711 

I couldn't find any better solution because none Event fit my needs but anyway it works. Hopefully this will help but please let me know in case of any further problems.

**Closed** 2023-02-07 06:57 UTC
